<template>
    <div class="chartElem">
        <div class="row">
            <highcharts class="chart" :options="chartOptions"></highcharts>
        </div>
    </div>
    </div>
</template>

<script>
    export default {
        data () {
            return {
                action: '/report',
                chartOptions: {
// Options will be generated by AJAX get
                }
            }
        },

        mounted() {
            axios.get(this.action).then((response) => {
                console.log(response.data[0]);
                this.chartOptions = response.data[0]; // Set chartOptions
            });
        },

        created () {
        },
        watch: {
        }
    }
</script>

